name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: another echo
        run: echo "another line"
  depending-job:
    needs: [reusable-job,another-job]
    runs-on: ubuntu-latest
    steps:
      - name: another echo
        run: echo "another line"
  